version: "3.9"

services:
  db:
    image: gusevang/custom_db:workversion
    container_name: db_test_2
    environment:
      - POSTGRES_PASSWORD=3846936720
    expose:
      - 5432
    restart: always

  web:
    image: gusevang/web:ver_test
    restart: always
    command: /app/AvitoTechTask
    container_name: test_2
    ports:
      - "1234:1234"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=3846936720
